### ISSUE TITLE
Criar entidade (classe) cliente e relacionados no sistema de agencia

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#27]
Definir atributos e relacionamentos

### Cliente

- nome (anotações`@NotBlank`)
- cpf `@column(unique = true)`
- dataNascimento: LocalDate
- celular `@NotBlank`
- fumante: boolean (não obrigatório, pois o cliente pode não informar ou não querer informar)
- endereco: Endereco

### Endereco

- logradouro: String `@NotBlank`
- cidade: Cidade `@NotNull`
- bairro: String

### Cidade e Estado

Criar campos conforme o script sql na raiz do repositório

**Comment by flaviomouracarvalho** [comment]
Me atribue.

**Comment by manoelcampos** [comment]
Como tá o andamento da issue?

**Comment by flaviomouracarvalho** [comment]
concluirei hj.
