### ISSUE TITLE
Criar entidade (classe) cliente e endereço no sistema de veículos

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#30]
Sugestões de atributos:

# Cliente

- cpf: String // anotações: `@Colunm(unique=true), @Cpf, @NotNull @NotBlank`
- nome `@NotNull @NotBlank`
- dataNascimento: LocalDate `@NotNull `
- endereco: Endereco `@NotNull `
- telefone: String `@NotNull @NotBlank`
- email: String `@Colunm(unique=true), @NotNull @NotBlank @Email`

# Endereco

- logradouro: String `@NotNull @NotBlank`
- cep: String `@NotNull @NotBlank`
- cidade: Cidade `@NotNull @NotBlank`

**Comment by BernardCarvalho** [comment]
Endereco

    logradouro: String @NotNull @NotBlank
    cep: String @NotNull @NotBlank
    cidade: **Cidade** @NotNull **@NotBlank**

Boa tarde professor, é necessário o uso da notação NotBlank em um objeto do tipo Cidade?

Imagino que talvez o atributo cidade possa ser do tipo String.

Aguardo o posicionamento do gerente de projetos.

**Comment by manoelcampos** [comment]
Respondido na PR #38
