### ISSUE TITLE
Adicionar biblioteca Open API e testar acesso à swagger UI ao sistema de hotelaria

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#35]
Seguir informações em https://springdoc.org

# PR Relacionada

- #41

**Comment by viniiciusmoura** [comment]
Me atribui

**Comment by manoelcampos** [comment]
Atribuído.

**Comment by viniiciusmoura** [comment]
![image](https://user-images.githubusercontent.com/82592484/204174983-5097efef-c4ed-4134-a375-f5906b639224.png)

Segue a imagem do teste que fiz.
