### ISSUE TITLE
Adicionar biblioteca Open API e testar acesso à swagger UI ao sistema de veículos

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#36]
Seguir informações em https://springdoc.org/

**Comment by BernardCarvalho** [comment]
@manoelcampos , gostaria de ter essa issue atribuida a mim.

**Comment by manoelcampos** [comment]
O comentário `Close #XX` é so na PR, para que quando for feito o merge da PR no branch master, a issue XX seja fechada automaticamente. Assim, aqui na issue não precisa colocar `Close #XX` como fez acima. Mas sem problema, é só apagar o teu comentário acima deste.
