### ISSUE TITLE
Adicionar biblioteca Open API ao sistema aéreo e testar acesso à swagger UI

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#37]
Seguir informações em https://springdoc.org/

# PR Relacionada

- #41

**Comment by nunesvictor** [comment]
Nesse caso será necessário criar os endpoints nessa mesma issue?

**Comment by nunesvictor** [comment]
Professor, agora que reparei que minha issue não estava vinculada a um PR, vou fazer agora

**Comment by nunesvictor** [comment]
> Seguir informações em https://springdoc.org/
> 
> # PR Relacionada
> * [Issue 36 - Adicionar biblioteca Open API e testar acesso à swagger UI ao sistema de veículos #41](https://github.com/iftopalmas/sistemas-viagens/pull/41)

Como vc pode ver esse PR é da issue 36 e não da 37
