### ISSUE TITLE
Criar hierarquia de herança para as classes de Pessoa no sistema aéreo

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#51]
Depende da finalização da PR #49 

## Pessoa

- Os atributos id, endereco e nome devem ser movidos da classe Cliente para pessoa

## PessoaFisica extends Pessoa

- Os atributos cpf e dataNascimento devem ser movidos de cliente para PessoaFisica

## Criar Piloto e alterar Cliente

Fazem composição com PessoaFisica por meio do atributo indicado abaixo.
Como um cliente pode ser piloto ou vice-versa em momentos diferentes,
não dá pra usar herança daqui pra baixo.

## Piloto

- pessoaFisica: PessoaFisica
- numeroBreve: String (número do brevê do piloto)
- validateBreve: LocalDate

### Cliente

- pessoaFisica: PessoaFisica
- numeroFidelidade: String = "" `@NotNull` (aceita blank)

**Comment by nunesvictor** [comment]
Posso padronizar os pacotes também? As entidades estão espalhadas por uns 3 pacotes e eu penso em colocar em `br.edu.ifto.sistemaaereo.models`

**Comment by manoelcampos** [comment]
Vai dar conflito demais pq tem um monte de PR aberta. A gente faz isso depois que fechar as PRs.

**Comment by nunesvictor** [comment]
Certo, obg pelo feedback
