### ISSUE TITLE
Criar classes Veiculo e relacionadas no sistema locadora

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#55]
Adicionar as anotações de relacionamento da JPA

## Marca

- descricao: String `@NotBlank @Column(unique = true)`

## Modelo

- descricao: String `@NotBlank @Column(unique = true)`
- marca: Marca `@NotNull`

## CategoriaVeiculo

- descricao: String `@NotBlank @Column(unique = true)`
- detalhes: String `@NotBlank` (detalhes sobre a categoria de veículo, como que tipo de acessários o veículo tem ou benefícios que clientes que alugam carros desta categoria ganham)

## Veiculo

- placa: String `@NotBlank @Column(unique = true)`
- modelo: Modelo
- categoria: CategoriaVeiculo `@NotNull`
- locadora: Locadora. Depende de #54: se não estiver concluída, comentar este atributo e adicionar comentário abaixo:

`//TODO depende de #54`

**Comment by lucasmmsouza** [comment]
falta a 54
