### ISSUE TITLE
Criar classe Reserva no sistema veículos

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#59]
# Reserva

- dataHoraCadastro: LocalDateTime (anotações `@NotNull`) com valor padrão igual a data/hora atual (definido no construtor)
- dataHoraRetiradaEsperada: LocalDateTime  `@NotNull` (data/hora de retirar o carro na locadora)
- dataHoraDevolucaoEsperada: LocalDateTime `@NotNull`
- cliente: Cliente  `@NotNull`

Se a #54 não estiver resolvida, comentar o campo e adicionar comentário `TODO: Depende de #54`

- locadoraRetirada: Locadora  `@NotNull`
- locadoraDevolucao: Locadora  `@NotNull`

# Notas

Não precisa criar getters e setters, pois estamos usando Lombok para criar automaticamente.
Basta anotar a classe com `@Getters @Setters`

## PRs relacionadas

- #54 
- #55

**Comment by HadisBra** [comment]
Deu erro Vou corrigir na proxima aula

**Comment by manoelcampos** [comment]
Vê se consegue corrigir antes, por favor.
Pra gente vê se agilizar, pois neste momento, temos algumas issues dependendo umas das outras.

**Comment by manoelcampos** [comment]
Vc fechou a issue, sem que ela tenha sido resolvida. Reabri aqui.

**Comment by HadisBra** [comment]
vou ter que refazer o codigo

Em qui., 1 de dez. de 2022 às 10:47, Manoel Campos ***@***.***>
escreveu:
