### ISSUE TITLE
Remover os métodos getters e setters e adicionar anotações `@Getter` e `@Setter`

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#64]
Como estamos usando Lombok, as anotações `@Getter @Setter` incluem estes elementos automaticamente.
Assim, remova qualquer getter e setter padrão (que não faça nenhuma validação) do código de todos os projetos.

Sempre executa um pull no master para pegar as últimas atualizações antes de criar novo branch para a issue.

**Comment by lucasTheodoroOliveira** [comment]
Ok , irei refazer


Em ter., 29 de nov. de 2022 às 09:15, Manoel Campos <
***@***.***> escreveu:

**Comment by manoelcampos** [comment]
Refazer? O que houve?
