### ISSUE TITLE
Padronizar os pacotes: as entidades estão espalhadas por uns 3 pacotes e eu penso em colocar em `br.edu.ifto.sistemaaereo.models`

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#72]
_Originally posted by @nunesvictor in https://github.com/iftopalmas/sistemas-viagens/issues/51#issuecomment-1334595260_

**Comment by nunesvictor** [comment]
aguardando os merges para evitar conflitos

**Comment by nunesvictor** [comment]
Tendo em vista que não há nenhuma outra issue aberta pra sistema-aereo, vou dar seguimento nessa
