### ISSUE TITLE
Criar API REST para gerenciar Pilotos no sistema aéreo

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#81]
A biblioteca [Spring Data REST](https://www.baeldung.com/spring-data-rest-intro) permite implementar automaticamente: o acesso ao BD (a partir de uma interface Repository criada por você) e a classe Rest Resource que conterá os métodos para gerenciar Pilotos a partir de uma API Web.

No entanto, como nosso repositório (a ser criada em um pacote repositories) de pilotos precisa de métodos personalizados, não sei se é possível indicar com Spring Data REST que desejamos usar um Repository que nós criamos. Veja a melhor opção.

A API deve fornecer métodos para:

- localizar piloto pelo ID
- localizar piloto pelo CPF
- cadastrar piloto: deve-se verificar se uma pessoa com o CPF informado já existe. Se existir, ela deve ser usada no cadastro do piloto e não criada nova pessoa. 
- atualizar piloto

# Issues Relacionadas

- #86

**Comment by nunesvictor** [comment]
Caso precise desses métodos personalizados podemos fazer com Impl class ou NamedQueries dependendo da complexidade

Vou começar fazendo dessa maneira, caso seja necessário a gente reescreve com class Impl

**Comment by manoelcampos** [comment]
Blz.
